version: '3.9'

services:
  db:
    image: ${DB_CLIENT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - 'pg-db:/var/lib/postgres'

  app:
    build:
      dockerfile: '.docker/Dockerfile'
      context: .
      target: develop
    env_file:
      - '.env'
    volumes:
      - './src:/code/src'
      - './package.json:/code/package.json'
      - './package-lock.json:/code/package-lock.json'
    ports:
      - '3001:3001'
    depends_on:
      - db

  migration:
    build:
      dockerfile: '.docker/Dockerfile'
      context: .
      target: build
    env_file:
      - '.env'
    command: ['npm', 'run', 'database:migrate']
    depends_on:
      - db

volumes:
  pg-db:
