version: '3.9'

networks:
  cs-network:
    driver: bridge

services:
  db:
    image: ${DB_CLIENT}
    container_name: db_cs
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pg-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - cs-network

  redis:
    image: ${REDIS_IMAGE}
    container_name: redis_cs
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-db:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - cs-network

  app:
    build:
      dockerfile: '.docker/Dockerfile'
      context: .
      target: develop
    env_file:
      - '.env'
    volumes:
      - './src:/code/src'
      - './package.json:/code/package.json'
      - './package-lock.json:/code/package-lock.json'
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - cs-network

volumes:
  pg-db:
  redis-db:
