version: "3.9"

networks:
  cs-network-main:
    external: true

services:
  db:
    image: postgres:latest
    container_name: db_cs
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_POSTGRES: ${DB_POSTGRES}
    ports:
      - "5434:5432"
    volumes:
      - cs-volume:/var/lib/postgresql/data/
    networks:
      - cs-network-main

  app:
    image: server_app
    container_name: app_cs
    build:
      dockerfile: "Dockerfile"
      context: .
      # target: release
    env_file:
      - ".env"
    volumes:
      - "./src:/code/src"
      - "./package.json:/code/package.json"
      - "./package-lock.json:/code/package-lock.json"
    ports:
      - "3001:3001"
    environment:
      - SERVER_PORT=3001
      - POSTGRES_CONNECTOR=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_POSTGRES}
    depends_on:
      - db
    networks:
      - cs-network-main

  nginx:
    build:
      context: .
      target: runner
    ports:
      - "3030:3030"
    networks:
      - cs-network-main
    volumes:
      - ../.nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  cs-volume:
