name: "Deploying backend DB migrations"
description: "Builds and pushes an image to a registry"

inputs:
  environment:
    description: "Environment name e.g. develop"
    required: true
  service_name:
    description: "Name of service to build e.g. craftscript"
    required: true
  image_name:
    description: "Name of the service to update"
    required: false
  image_tag:
    description: "Name of image tag (usually build number or commit hash)"
    required: true
  registry_user:
    description: "Docker registry user"
    required: true
  registry_token:
    description: "Docker registry token"
    required: true

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      run: |
        echo ${{ inputs.registry_token }} | docker login -u ${{ inputs.registry_user }} --password-stdin
      shell: bash

    - name: Fill in the new image ID
      run: |
        docker build -t {{ inputs.registry_user }}/{{ inputs.image_user }}:{{ inputs.image_tag }}
      shell: bash
