name: "Deploying backend DB migrations"
description: "Builds an image on remote"

inputs:
  remote_host:
    description: "Remote host connector"
    required: true
  remote_user:
    description: "SSH private key"
    required: true
  ftp_password:
    description: "Password to ftp client"
    required: true
  ftp_path:
    description: "Path to ftp repository"
    required: true

runs:
  using: composite
  steps:
    - name: Run migration scripts
      uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.remote_host }}
          username: ${{ inputs.remote_user }}
          password: ${{ inputs.ftp_password }}
          script: |
            cd ${{ secrets.FTP_PATH }}
            make docker-db-migrate
