name: "Build and push image"
description: "Builds and pushes an image to a registry"

inputs:
  service_name:
    description: "Service to build e.g. dataset"
    required: true
  repo_name:
    description: "Image registry repo e.g. my_image_repo"
    required: true
  image_tag:
    description: "Name of image tag (usually build number or commit hash)"
    required: true

runs:
  using: composite
  steps:
    - name: Build, tag, and push ${{ inputs.service_name }} image to registry
      # working-directory: ./services/${{ inputs.service_name }}
      run: |
        docker build -t {{ inputs.repo_name }}:${{ inputs.image_tag }} .
        docker push ${{ inputs.repo_name }}:${{ inputs.image_tag }}
