export const coinGeckoIdsBySymbol: Record<string, string> = {
    AAVE: 'aave',
    ADA: 'cardano',
    ALEO: 'aleo',
    APT: 'aptos',
    ARB: 'arbitrum',
    AURORA: 'aurora-near',
    AVAX: 'avalanche-2',
    BCH: 'bitcoin-cash',
    BERA: 'berachain-bera',
    BNB: 'binancecoin',
    BOME: 'book-of-meme',
    BTC: 'bitcoin',
    DAI: 'dai',
    DOGE: 'dogecoin',
    ETH: 'ethereum',
    GMX: 'gmx',
    GNO: 'gnosis',
    KAITO: 'kaito',
    KNC: 'kyber-network-crystal',
    LINK: 'chainlink',
    LTC: 'litecoin',
    MELANIA: 'melania-meme',
    MOG: 'mog-coin',
    NEAR: 'near',
    OKB: 'okb',
    OP: 'optimism',
    PENGU: 'pudgy-penguins',
    PEPE: 'pepe',
    POL: 'polygon-ecosystem-token',
    PUBLIC: 'publicai',
    REF: 'ref-finance',
    SAFE: 'safe',
    SHIB: 'shiba-inu',
    SOL: 'solana',
    SPX: 'spx6900',
    STRK: 'starknet',
    SUI: 'sui',
    SWEAT: 'sweatcoin',
    TON: 'the-open-network',
    TRUMP: 'official-trump',
    TRX: 'tron',
    TURBO: 'turbo',
    UNI: 'uniswap',
    USDC: 'usd-coin',
    USDT: 'tether',
    VVV: 'venice-token',
    WBTC: 'wrapped-bitcoin',
    WETH: 'weth',
    WIF: 'dogwifcoin',
    WNEAR: 'wrapped-near',
    XAUT: 'tether-gold',
    XLM: 'stellar',
    XRP: 'ripple',
    ZEC: 'zcash',
};

export function coinGeckoIdForSymbol(symbol: string, configured?: string): string | undefined {
    const override = configured?.trim();
    if (override) {
        return override;
    }

    return coinGeckoIdsBySymbol[symbol.trim().toUpperCase()];
}
