name: Reusable - Build Backend

on:
  workflow_call:
    inputs:
      service_name:
        description: "Application name you want to deploy (dataset, run, project, etc.)"
        required: false
        type: string
        default: ""
      environment:
        description: "Environment name you want to deploy to (dev, test, etc.)"
        required: false
        type: string
        default: ""
    secrets:
      REMOTE_USER:
        required: true
      REMOTE_HOST:
        required: true
      REMOTE_KEY:
        required: true
      FTP_PASSWORD:
        required: true
      FTP_PATH:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service_name: [ "${{ inputs.service_name }}" ]
        environment: [ "${{ inputs.environment }}" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Migrate ${{ matrix.service_name }} from ${{ matrix.environment }} to remote
        uses: ./.github/actions/copy-to
        with:
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          ftp_path: ${{ secrets.FTP_PATH }}

      - name: Building and pushing image
        uses: ./.github/actions/build-and-push
        with:
          service_name: ${{ matrix.service_name }}
          repo_name: "vodis-${{ matrix.environment }}-${{ matrix.service_name }}"
          image_tag: "${{ github.run_number }}"
