name: Reusable - CVE Scanning

on:
  workflow_call:
    inputs:
      service_name:
        description: ""
        required: true
        type: string
      service_path:
        description: ""
        required: true
        type: string
        default: .

jobs:
  code-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service_name: ["${{ inputs.service_name }}"]
        service_path: ["${{ inputs.service_path }}"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CVE Scanning - Dependencies
        uses: ./.github/actions/security-scan
        with:
          scan_type: fs
          folder_to_scan: ${{ matrix.service_path }}

      - name: CVE Scanning - Config
        uses: ./.github/actions/security-scan
        with:
          scan_type: config
          folder_to_scan: ${{ matrix.service_path }}
